##
## EPITECH PROJECT, 2021
## B_OOP_400_LIL_4_1_arcade_achille_bourgault
## File description:
## Makefile
##

all:
	make -C./src
	make -C./src/libs/sfml
	make -C./src/libs/sdl2
	make -C./src/libs/ncurses
	make -C./src/games/nibbler
	make -C./src/games/pacman

clean:
	make clean -C./src
	make clean -C./src/libs/sfml
	make clean -C./src/libs/sdl2
	make clean -C./src/libs/ncurses
	make clean -C./src/games/nibbler
	make clean -C./src/games/pacman

fclean:
	make fclean -C./src
	make fclean -C./src/libs/sfml
	make fclean -C./src/libs/sdl2
	make fclean -C./src/libs/ncurses
	make fclean -C./src/games/nibbler
	make fclean -C./src/games/pacman

re:
	make re -C./src
	make re -C./src/libs/sfml
	make re -C./src/libs/sdl2
	make re -C./src/libs/ncurses
	make re -C./src/games/nibbler
	make re -C./src/games/pacman

core:
	make -C./src

games:
	make -C./src/games/nibbler
	make -C./src/games/pacman

graphicals:
	make -C./src/libs/sfml
	make -C./src/libs/sdl2
	make -C./src/libs/ncurses